USE webproject;


DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Smartphones;
DROP TABLE IF EXISTS Laptops;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS QuestionAndAnswers;
DROP TABLE IF EXISTS Carts;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Admins;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Users;
